
- name: "Atualizar os pacotes"
  apt: >
    upgrade=yes
    update_cache=yes
    cache_valid_time=3600

- name: "Install aptitude using apt"
  apt: name=aptitude state=latest

- name: "Install required system packages"
  apt: name={{ item }} state=latest
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: "Add Docker GPG apt Key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add Docker Repository"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: "Update apt and install docker-ce"
  apt: name=docker-ce state=latest

- name: "Install Docker Module for Python"
  pip:
    name: docker

- name: "copy Docker Compose files"
  copy:
    src: docker/docker-compose.yml
    dest: docker/docker-compose.yml

- name: "deploy Docker Compose stack"
  docker_compose:
    project_src: docker/ 
    files:
    - docker-compose.yml
